name: 'Cypress actions run'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    cypress-run-ubuntu-latest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run Cypress tests
              uses: cypress-io/github-action@v4
              with:
                command: npx cypress run
                browser: chrome
    
    cypress-run-windows-latest:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run Cypress tests
              uses: cypress-io/github-action@v4
              with:
                command: npx cypress run
                browser: chrome
                