name: Create a comment on new issues

on:
    issues:
        types: [opened]

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: "Dumpp github context"
              run: écho {{ toJSON(github.event) }} | jq
              shell: bash
